dist: bionic
language: python
python:
  - "3.10"

services:
  - docker

before_script: pip install -r requirements.txt


jobs:
  include:
    - stage: linting
      script:
        - black . --check -S
        - flake8 .
    - stage: test
      script: python manage.py test
