# Generated by Django 3.2 on 2022-02-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walker_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressdetails',
            name='postcode',
        ),
        migrations.AddField(
            model_name='addressdetails',
            name='address',
            field=models.CharField(max_length=100, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='addressdetails',
            name='country',
            field=models.CharField(max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='addressdetails',
            name='county',
            field=models.CharField(max_length=100, null=True, verbose_name='County'),
        ),
        migrations.AddField(
            model_name='addressdetails',
            name='latitude',
            field=models.CharField(max_length=50, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='addressdetails',
            name='longtitude',
            field=models.CharField(max_length=50, null=True, verbose_name='Longtitude'),
        ),
        migrations.AddField(
            model_name='addressdetails',
            name='post_code',
            field=models.CharField(max_length=8, null=True, verbose_name='Post Code'),
        ),
        migrations.AlterField(
            model_name='addressdetails',
            name='address_1',
            field=models.CharField(max_length=100, null=True, verbose_name='Address 1'),
        ),
        migrations.AlterField(
            model_name='addressdetails',
            name='address_2',
            field=models.CharField(max_length=100, null=True, verbose_name='Address 2'),
        ),
        migrations.AlterField(
            model_name='addressdetails',
            name='town',
            field=models.CharField(max_length=100, null=True, verbose_name='Town/City'),
        ),
    ]
