# Generated by Django 3.2 on 2022-02-21 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('walker_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetsitterDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='walkeruser',
            name='petsitter_details',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='walker_profile.petsitterdetails'),
        ),
    ]
