# Generated by Django 3.2 on 2022-02-14 11:15

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('walker_profile', '0002_alter_walkeruser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=200, null=True, unique=True)),
                ('town', models.CharField(max_length=200, null=True)),
                ('address_1', models.CharField(max_length=128)),
                ('address_2', models.CharField(max_length=128)),
                ('postcode', models.CharField(max_length=200, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='walkeruser',
            name='contact_details',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='walker_profile.contactdetails'),
        ),
    ]
