# Generated by Django 3.2 on 2022-02-22 14:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('walker_profile', '0002_auto_20220221_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='petsitterdetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ServiceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(null=True)),
                ('is_small_dog', models.BooleanField(null=True)),
                ('s_price_hour', models.CharField(max_length=10, null=True)),
                ('s_price_day', models.CharField(max_length=10, null=True)),
                ('is_medium_dog', models.BooleanField(null=True)),
                ('m_price_hour', models.CharField(max_length=10, null=True)),
                ('m_price_day', models.CharField(max_length=10, null=True)),
                ('is_big_dog', models.BooleanField(null=True)),
                ('b_price_hour', models.CharField(max_length=10, null=True)),
                ('b_price_day', models.CharField(max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('petsitter_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='walker_profile.petsitterdetails')),
                ('service_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='walker_profile.servicetypes')),
            ],
        ),
    ]
