# Generated by Django 3.2 on 2022-03-01 14:12

from django.db import migrations, models
import walker_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('walker_profile', '0003_alter_walkeruser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walkeruser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar_images/', validators=[walker_profile.models.WalkerUser.validate_image]),
        ),
    ]
