# Generated by Django 3.2 on 2022-03-03 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('walker_profile', '0004_alter_walkeruser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
