# Generated by Django 3.2 on 2022-02-24 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('walker_profile', '0004_auto_20220223_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetails',
            name='service_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='walker_profile.servicetypes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicedetails',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='walker_profile.walkeruser'),
            preserve_default=False,
        ),
    ]
