# Generated by Django 3.2 on 2022-03-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walker_profile', '0005_alter_servicedetails_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressdetails',
            name='longtitude',
        ),
        migrations.AddField(
            model_name='addressdetails',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='addressdetails',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
