# Generated by Django 3.2 on 2022-03-06 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walker_profile', '0006_auto_20220303_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addressdetails',
            old_name='postcode',
            new_name='postcodeaaaa',
        ),
    ]
