# Generated by Django 3.2 on 2022-03-06 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walker_profile', '0007_rename_postcode_addressdetails_postcodeaaaa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addressdetails',
            old_name='postcodeaaaa',
            new_name='postcode',
        ),
    ]
