# Generated by Django 3.2 on 2022-03-06 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walker_profile', '0008_rename_postcodeaaaa_addressdetails_postcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicetypes',
            old_name='types',
            new_name='type',
        ),
    ]
