# Generated by Django 3.2 on 2022-04-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walker_profile', '0015_alter_servicedetails_is_small_dog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetails',
            name='is_small_dog',
            field=models.BooleanField(null=True),
        ),
    ]
