# Generated by Django 3.2 on 2022-03-25 09:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='NewsletterUser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 3, 25, 9, 36, 56, 455614, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
