# Generated by Django 3.2 on 2022-03-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_alter_newsletteruser_is_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletteruser',
            name='unsubscribed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
