# Generated by Django 3.2 on 2022-03-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_petsitterreview_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petsitterreview',
            name='is_admin_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='petsitterreview',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
