# Generated by Django 3.2 on 2022-03-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_alter_petsitterreview_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petsitterreview',
            name='stars',
            field=models.CharField(choices=[('0', '☆'), ('1', '☆'), ('2', '☆'), ('3', '☆'), ('4', '☆')], max_length=11),
        ),
    ]
