# Generated by Django 3.2 on 2022-03-11 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0010_alter_petsitterreview_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petsitterreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='petsitterreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
