# Generated by Django 3.2 on 2022-03-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_auto_20220311_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petsitterreview',
            name='stars',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
